/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel
 */
public class Home extends javax.swing.JFrame {

    int x,y;
    int colorValue;
    Color btndefault = new Color(23,35,51);
    Connection conn;
    
    
    public Home() {
        initComponents();
        conn = DBConnection.connect();
        
        
        DesktopPane.removeAll();
        Main ma = new Main();
        DesktopPane.add(ma).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Dashboard_Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        D1Nav = new javax.swing.JLabel();
        D2Nav = new javax.swing.JLabel();
        D3Nav = new javax.swing.JLabel();
        D4Nav = new javax.swing.JLabel();
        D5Nav = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jDesktopPanel5 = new javax.swing.JPanel();
        DesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 244, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        Dashboard_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imresizer-1733421728392.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVENTORY SYSTEM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MMPAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Dashboard_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Dashboard_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        D1Nav.setBackground(new java.awt.Color(244, 244, 255));
        D1Nav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        D1Nav.setForeground(new java.awt.Color(0, 0, 51));
        D1Nav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dashboard.png"))); // NOI18N
        D1Nav.setText("         DashBoard");
        D1Nav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D1Nav.setOpaque(true);
        D1Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D1NavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                D1NavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                D1NavMouseExited(evt);
            }
        });

        D2Nav.setBackground(new java.awt.Color(244, 244, 255));
        D2Nav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        D2Nav.setForeground(new java.awt.Color(0, 0, 51));
        D2Nav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/products.png"))); // NOI18N
        D2Nav.setText("       Products");
        D2Nav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D2Nav.setOpaque(true);
        D2Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D2NavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                D2NavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                D2NavMouseExited(evt);
            }
        });

        D3Nav.setBackground(new java.awt.Color(244, 244, 255));
        D3Nav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        D3Nav.setForeground(new java.awt.Color(0, 0, 51));
        D3Nav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sales.png"))); // NOI18N
        D3Nav.setText("         Sales");
        D3Nav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D3Nav.setOpaque(true);
        D3Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D3NavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                D3NavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                D3NavMouseExited(evt);
            }
        });

        D4Nav.setBackground(new java.awt.Color(244, 244, 255));
        D4Nav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        D4Nav.setForeground(new java.awt.Color(0, 0, 51));
        D4Nav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reports.png"))); // NOI18N
        D4Nav.setText("         Report");
        D4Nav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D4Nav.setOpaque(true);
        D4Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D4NavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                D4NavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                D4NavMouseExited(evt);
            }
        });

        D5Nav.setBackground(new java.awt.Color(244, 244, 255));
        D5Nav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        D5Nav.setForeground(new java.awt.Color(0, 0, 51));
        D5Nav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin.png"))); // NOI18N
        D5Nav.setText("         Admin");
        D5Nav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D5Nav.setOpaque(true);
        D5Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D5NavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                D5NavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                D5NavMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(D5Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D4Nav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D3Nav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D2Nav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(D1Nav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(D1Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(D2Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(D3Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(D4Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(D5Nav, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 356, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 770));

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closeDash.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(1044, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1070, 30));

        jDesktopPanel5.setBackground(new java.awt.Color(255, 255, 255));

        DesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPanel5Layout = new javax.swing.GroupLayout(jDesktopPanel5);
        jDesktopPanel5.setLayout(jDesktopPanel5Layout);
        jDesktopPanel5Layout.setHorizontalGroup(
            jDesktopPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        jDesktopPanel5Layout.setVerticalGroup(
            jDesktopPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        jPanel1.add(jDesktopPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 1070, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void D1NavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1NavMouseEntered
        // TODO add your handling code here:
        D1Nav.setBackground(new Color(210, 210, 240));
    }//GEN-LAST:event_D1NavMouseEntered

    private void D1NavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1NavMouseExited
        // TODO add your handling code here:
        D1Nav.setBackground(new Color(244,244,255));
    }//GEN-LAST:event_D1NavMouseExited

    private void D2NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2NavMouseClicked
        DesktopPane.removeAll();
        ProductList pl = new ProductList();
        DesktopPane.add(pl).setVisible(true);
    }//GEN-LAST:event_D2NavMouseClicked

    private void D2NavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2NavMouseEntered
        // TODO add your handling code here:
        D2Nav.setBackground(new Color(210, 210, 240));
    }//GEN-LAST:event_D2NavMouseEntered

    private void D2NavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2NavMouseExited
        D2Nav.setBackground(new Color(244,244,255));
    }//GEN-LAST:event_D2NavMouseExited

    private void D3NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3NavMouseClicked
        DesktopPane.removeAll();
        Sales sa = new Sales();
        DesktopPane.add(sa).setVisible(true);
    }//GEN-LAST:event_D3NavMouseClicked

    private void D3NavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3NavMouseEntered
        D3Nav.setBackground(new Color(210, 210, 240));
    }//GEN-LAST:event_D3NavMouseEntered

    private void D3NavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3NavMouseExited
        D3Nav.setBackground(new Color(244,244,255));
    }//GEN-LAST:event_D3NavMouseExited

    private void D4NavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4NavMouseEntered
        D4Nav.setBackground(new Color(210, 210, 240));
    }//GEN-LAST:event_D4NavMouseEntered

    private void D4NavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4NavMouseExited
        D4Nav.setBackground(new Color(244,244,255));
    }//GEN-LAST:event_D4NavMouseExited

    private void D5NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D5NavMouseClicked
        Admin reg = new Admin();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_D5NavMouseClicked

    private void D5NavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D5NavMouseEntered
        D5Nav.setBackground(new Color(210, 210, 240));
    }//GEN-LAST:event_D5NavMouseEntered

    private void D5NavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D5NavMouseExited
        D5Nav.setBackground(new Color(244,244,255));
    }//GEN-LAST:event_D5NavMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to logout application?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void D1NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1NavMouseClicked
        DesktopPane.removeAll();
        Main ma = new Main();
        DesktopPane.add(ma).setVisible(true);
    }//GEN-LAST:event_D1NavMouseClicked

    private void D4NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4NavMouseClicked
        DesktopPane.removeAll();
        Report re = new Report();
        DesktopPane.add(re).setVisible(true);
    }//GEN-LAST:event_D4NavMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel D1Nav;
    private javax.swing.JLabel D2Nav;
    private javax.swing.JLabel D3Nav;
    private javax.swing.JLabel D4Nav;
    private javax.swing.JLabel D5Nav;
    private javax.swing.JLabel Dashboard_Logo;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jDesktopPanel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
