/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Angel
 */
public class Main extends javax.swing.JInternalFrame {

    /**
     * Creates new form Main
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    String iid;
    String iname;
    String category;
    String serialno;
    String costprice;
    String sellprice;
    String quantity;
    Connection con;

    public Main() {
        initComponents();
        con = DBConnection.connect();
        updateDashboard(); // Load dashboard data
        updateStockAlerts();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    private void updateDashboard() {
        try {
            // Total Items
            String totalItemsQuery = "SELECT SUM(quantity) AS total FROM productlist";
            pst = con.prepareStatement(totalItemsQuery);
            rs = pst.executeQuery();
            if (rs.next()) {
                totalitems.setText(rs.getString("total"));
            }

            // Total Sales
            String totalSalesQuery = "SELECT COUNT(*) AS total FROM sales";
            pst = con.prepareStatement(totalSalesQuery);
            rs = pst.executeQuery();
            if (rs.next()) {
                totalsales.setText(rs.getString("total"));
            }

            // Total Revenue
            String totalRevenueQuery = "SELECT SUM(due) AS total FROM sales";
            pst = con.prepareStatement(totalRevenueQuery);
            rs = pst.executeQuery();
            if (rs.next()) {
                totalrevenue.setText(rs.getString("total"));
            }

            // Low Stock Alerts
            String lowStockQuery = "SELECT COUNT(*) AS total FROM productlist WHERE quantity < 5";
            pst = con.prepareStatement(lowStockQuery);
            rs = pst.executeQuery();
            if (rs.next()) {
                int lowStockCount = rs.getInt("total");

                // Update the table or component accordingly
                DefaultTableModel model = (DefaultTableModel) tblalerts.getModel();
                model.setRowCount(0); // Clear existing rows
                model.addRow(new Object[]{"Low Stock Products", lowStockCount});
            }
            updateStockAlerts();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating dashboard: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        D4 = new javax.swing.JPanel();
        D3Header3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        totalrevenue = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        D5 = new javax.swing.JPanel();
        D2Header3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        totalsales = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        D3 = new javax.swing.JPanel();
        D1Header3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalitems = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        D6 = new javax.swing.JPanel();
        D4Header4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblalerts = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 740));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");

        D4.setBackground(new java.awt.Color(30, 81, 123));
        D4.setPreferredSize(new java.awt.Dimension(312, 246));

        D3Header3.setBackground(new java.awt.Color(20, 53, 81));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Revenue");

        javax.swing.GroupLayout D3Header3Layout = new javax.swing.GroupLayout(D3Header3);
        D3Header3.setLayout(D3Header3Layout);
        D3Header3Layout.setHorizontalGroup(
            D3Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D3Header3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        D3Header3Layout.setVerticalGroup(
            D3Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D3Header3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        totalrevenue.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        totalrevenue.setForeground(new java.awt.Color(255, 255, 255));
        totalrevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalrevenue.setText("0");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total Revenue");

        javax.swing.GroupLayout D4Layout = new javax.swing.GroupLayout(D4);
        D4.setLayout(D4Layout);
        D4Layout.setHorizontalGroup(
            D4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(D3Header3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(100, 100, 100))
            .addGroup(D4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(totalrevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        D4Layout.setVerticalGroup(
            D4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D4Layout.createSequentialGroup()
                .addComponent(D3Header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalrevenue)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        D5.setBackground(new java.awt.Color(141, 175, 228));

        D2Header3.setBackground(new java.awt.Color(90, 139, 215));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sales");

        javax.swing.GroupLayout D2Header3Layout = new javax.swing.GroupLayout(D2Header3);
        D2Header3.setLayout(D2Header3Layout);
        D2Header3Layout.setHorizontalGroup(
            D2Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D2Header3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        D2Header3Layout.setVerticalGroup(
            D2Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D2Header3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        totalsales.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        totalsales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalsales.setText("0");

        jLabel21.setText("Total Sales");

        javax.swing.GroupLayout D5Layout = new javax.swing.GroupLayout(D5);
        D5.setLayout(D5Layout);
        D5Layout.setHorizontalGroup(
            D5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(D2Header3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(D5Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(totalsales, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        D5Layout.setVerticalGroup(
            D5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D5Layout.createSequentialGroup()
                .addComponent(D2Header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(totalsales)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(25, 25, 25))
        );

        D3.setBackground(new java.awt.Color(222, 233, 241));

        D1Header3.setBackground(new java.awt.Color(201, 219, 232));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Items");

        javax.swing.GroupLayout D1Header3Layout = new javax.swing.GroupLayout(D1Header3);
        D1Header3.setLayout(D1Header3Layout);
        D1Header3Layout.setHorizontalGroup(
            D1Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D1Header3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        D1Header3Layout.setVerticalGroup(
            D1Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D1Header3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        totalitems.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        totalitems.setForeground(new java.awt.Color(0, 0, 102));
        totalitems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalitems.setText("0");

        jLabel8.setText("Total Items in Stock");

        javax.swing.GroupLayout D3Layout = new javax.swing.GroupLayout(D3);
        D3.setLayout(D3Layout);
        D3Layout.setHorizontalGroup(
            D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(D1Header3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(D3Layout.createSequentialGroup()
                .addGroup(D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(D3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel8))
                    .addGroup(D3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(totalitems, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        D3Layout.setVerticalGroup(
            D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D3Layout.createSequentialGroup()
                .addComponent(D1Header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalitems)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        D6.setBackground(new java.awt.Color(244, 244, 255));

        D4Header4.setBackground(new java.awt.Color(14, 26, 81));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stock Alerts");

        javax.swing.GroupLayout D4Header4Layout = new javax.swing.GroupLayout(D4Header4);
        D4Header4.setLayout(D4Header4Layout);
        D4Header4Layout.setHorizontalGroup(
            D4Header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D4Header4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        D4Header4Layout.setVerticalGroup(
            D4Header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D4Header4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblalerts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Category", "Quantity", "Stock Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblalerts);

        javax.swing.GroupLayout D6Layout = new javax.swing.GroupLayout(D6);
        D6.setLayout(D6Layout);
        D6Layout.setHorizontalGroup(
            D6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(D4Header4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        D6Layout.setVerticalGroup(
            D6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D6Layout.createSequentialGroup()
                .addComponent(D4Header4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(D6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(D5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(D4, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void theader() {
        JTableHeader thead = tblalerts.getTableHeader();
        thead.setForeground(Color.decode("#102C57"));
        thead.setBackground(Color.decode("#ECEBDE"));
        thead.setFont(new Font("Tahome", Font.BOLD, 14));

        TableColumn col = tblalerts.getColumnModel().getColumn(0);
        col.setPreferredWidth(100);
        TableColumn col1 = tblalerts.getColumnModel().getColumn(1);
        col1.setPreferredWidth(184);
        TableColumn col2 = tblalerts.getColumnModel().getColumn(2);
        col2.setPreferredWidth(120);
        TableColumn col3 = tblalerts.getColumnModel().getColumn(3);
        col3.setPreferredWidth(120);

        // Set a custom renderer to apply foreground/background color conditionally
        tblalerts.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value,
                        isSelected, hasFocus, row, column);

                String stockStatus = (String) table.getValueAt(row, 3); // "Stock Status" is in column 3
                if (stockStatus.equals("Low Stock")) {
                    cell.setBackground(Color.YELLOW); // Yellow for Low Stock
                    cell.setForeground(Color.BLACK);
                } else if (stockStatus.equals("Out of Stock")) {
                    cell.setBackground(Color.RED); // Red for Out of Stock
                    cell.setForeground(Color.WHITE);
                } else {
                    cell.setBackground(Color.WHITE); // Default background
                    cell.setForeground(Color.BLACK);
                }

                return cell;
            }
        });
    }

    private void updateStockAlerts() {
        try {
            // Clear previous data in the alert table
            DefaultTableModel alertModel = (DefaultTableModel) tblalerts.getModel();
            alertModel.setRowCount(0); // Remove all existing rows

            // Query to get all products with their quantities, min_stock, and max_stock
            String query = "SELECT item_name, category, quantity, min_stock, max_stock FROM productlist";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();

            // Iterate through all the products and determine stock status
            while (rs.next()) {
                String itemName = rs.getString("item_name");
                String category = rs.getString("category");
                int quantity = rs.getInt("quantity");
                int minStock = rs.getInt("min_stock");
                int maxStock = rs.getInt("max_stock");

                // Determine stock status
                String stockStatus = ""; // Default stock status

                if (quantity == 0) {
                    stockStatus = "Out of Stock";
                } else if (quantity <= minStock) {
                    stockStatus = "Low Stock";
                } else if (quantity >= maxStock) {
                    stockStatus = "Overstock";
                }

                // Only add the row if the product has one of the required stock statuses
                if (!stockStatus.isEmpty()) {
                    alertModel.addRow(new Object[]{
                        itemName, // Product Name
                        category, // Product Category
                        quantity, // Product Quantity
                        stockStatus // Stock Status (Low Stock, Out of Stock, Overstock)
                    });
                }
            }

            theader();
        } catch (Exception e) {
            // Handle any errors that occur during the database query
            JOptionPane.showMessageDialog(this, "Error updating stock alerts: " + e.getMessage());
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel D1Header3;
    private javax.swing.JPanel D2Header3;
    private javax.swing.JPanel D3;
    private javax.swing.JPanel D3Header3;
    private javax.swing.JPanel D4;
    private javax.swing.JPanel D4Header4;
    private javax.swing.JPanel D5;
    private javax.swing.JPanel D6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblalerts;
    private javax.swing.JLabel totalitems;
    private javax.swing.JLabel totalrevenue;
    private javax.swing.JLabel totalsales;
    // End of variables declaration//GEN-END:variables
}
