package Interface;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Angel
 */
public class Report extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddItem
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    Connection con;

    public Report() {
        initComponents();
        con = DBConnection.connect();
        salelord();
        stocklord();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    private void salelord() {
        try {
            String sql = "SELECT `sale_id` as 'Sale ID', `item_id` as 'Item ID', `unit_price` as 'Unit Price', `quantity` as 'Quantity', `total_price` as 'Total Price', `discount` as 'Discount', `due` as 'Due Amount', `cash` as 'Cash', `change` as 'Change', `date` as 'Date' FROM `sales`";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblsales.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            theader();

        } catch (Exception e) {
            e.printStackTrace(); // Always print stack trace for debugging
        }
    }

    private void stocklord() {
        try {
            String sql = "SELECT `item_id` as 'Item ID', `item_name` as 'Item Name', `category` as 'Category', `serial_no` as 'Serial No.', `cost_price` as 'Cost Price', `sale_price` as 'Sale Price', `quantity` as 'Quantity', `min_stock` as 'MIN', `max_stock` as 'MAX', `image` as 'Image' FROM `productlist`";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace(); // Always print stack trace for debugging
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnprocess = new javax.swing.JButton();
        printsales = new javax.swing.JButton();
        btnclearsale = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsales = new javax.swing.JTable();
        fdate = new com.toedter.calendar.JDateChooser();
        tdate = new com.toedter.calendar.JDateChooser();
        total = new javax.swing.JLabel();
        totalsales = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcategory = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblstock = new javax.swing.JTable();
        btnclearstock = new javax.swing.JButton();
        printstock = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 740));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 244, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Sales");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("From");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("To");

        btnprocess.setBackground(new java.awt.Color(0, 102, 0));
        btnprocess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprocess.setForeground(new java.awt.Color(255, 255, 255));
        btnprocess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/process.png"))); // NOI18N
        btnprocess.setText("PROCESS");
        btnprocess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprocessMouseClicked(evt);
            }
        });

        printsales.setBackground(new java.awt.Color(0, 0, 102));
        printsales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printsales.setForeground(new java.awt.Color(255, 255, 255));
        printsales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-print-20.png"))); // NOI18N
        printsales.setText("PRINT");
        printsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printsalesMouseClicked(evt);
            }
        });
        printsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printsalesActionPerformed(evt);
            }
        });

        btnclearsale.setBackground(new java.awt.Color(204, 0, 0));
        btnclearsale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclearsale.setForeground(new java.awt.Color(255, 255, 255));
        btnclearsale.setText("CLEAR");
        btnclearsale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearsaleMouseClicked(evt);
            }
        });

        tblsales.setBackground(new java.awt.Color(244, 244, 255));
        tblsales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblsales.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblsales);

        fdate.setDateFormatString("yyyy-MM-dd");

        tdate.setDateFormatString("yyyy-MM-dd");

        total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        total.setText("TOTAL SALES:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalsales, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnprocess)
                                .addGap(36, 36, 36)
                                .addComponent(printsales, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(btnclearsale, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addComponent(fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(totalsales, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printsales, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclearsale, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprocess, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 480, 590));

        jPanel4.setBackground(new java.awt.Color(244, 244, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Stock");

        txtcategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoryActionPerformed(evt);
            }
        });
        txtcategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcategoryKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Category");

        tblstock.setBackground(new java.awt.Color(244, 244, 255));
        tblstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblstock.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblstock);

        btnclearstock.setBackground(new java.awt.Color(204, 0, 0));
        btnclearstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclearstock.setForeground(new java.awt.Color(255, 255, 255));
        btnclearstock.setText("CLEAR");
        btnclearstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearstockMouseClicked(evt);
            }
        });

        printstock.setBackground(new java.awt.Color(0, 0, 102));
        printstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printstock.setForeground(new java.awt.Color(255, 255, 255));
        printstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-print-20.png"))); // NOI18N
        printstock.setText("PRINT");
        printstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printstockMouseClicked(evt);
            }
        });
        printstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printstockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(printstock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclearstock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printstock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclearstock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 480, 590));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("REPORT");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoryActionPerformed

    private void printsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printsalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printsalesActionPerformed

    private void printstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printstockActionPerformed

    private void btnprocessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprocessMouseClicked

        String salefdate = ((JTextField) fdate.getDateEditor().getUiComponent()).getText();
        String saletdate = ((JTextField) tdate.getDateEditor().getUiComponent()).getText();
        theader();
        if (salefdate.length() > 0 && saletdate.isEmpty()) {
            try {
                // Query to get sales data for the selected date
                String sql = "SELECT `sale_id` as 'Sale ID', `item_id` as 'Item ID', `unit_price` as 'Unit Price', `quantity` as 'Quantity', `total_price` as 'Total Price', `discount` as 'Discount', `due` as 'Due Amount', `cash` as 'Cash', `change` as 'Change', `date` as 'Date' FROM `sales` where date='" + salefdate + "'";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                tblsales.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                theader();

                // Calculate the total sales for the selected date
                String totalsql = "SELECT SUM(total_price) as TotalSales FROM `sales` WHERE date='" + salefdate + "'";
                pst = con.prepareStatement(totalsql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    double totalSales = rs.getDouble("TotalSales");

                    // Update the totalsales JLabel to display the total sales
                    totalsales.setText(String.format("%.2f", totalSales));
                }

            } catch (Exception e) {
                e.printStackTrace(); // Always print stack trace for debugging
            }
        } else if (saletdate.length() > 0 && salefdate.length() > 0) {

            try {
                // Query to get sales data for the date range
                String sql = "SELECT `sale_id` as 'Sale ID', `item_id` as 'Item ID', `unit_price` as 'Unit Price', `quantity` as 'Quantity', `total_price` as 'Total Price', `discount` as 'Discount', `due` as 'Due Amount', `cash` as 'Cash', `change` as 'Change', `date` as 'Date' FROM `sales` where date between '" + salefdate + "' and '" + saletdate + "'";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                tblsales.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                theader();

                // Calculate the total sales for the date range
                String totalsql = "SELECT SUM(total_price) as TotalSales FROM `sales` WHERE date BETWEEN '" + salefdate + "' AND '" + saletdate + "'";
                pst = con.prepareStatement(totalsql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    double totalSales = rs.getDouble("TotalSales");

                    // Update the totalsales JLabel to display the total sales for the range
                    totalsales.setText(String.format("%.2f", totalSales));
                }

            } catch (Exception e) {
                e.printStackTrace(); // Always print stack trace for debugging
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Select date");
        }
    }//GEN-LAST:event_btnprocessMouseClicked

    private void theader() {
        JTableHeader thead = tblstock.getTableHeader();
        thead.setForeground(Color.decode("#102C57"));
        thead.setBackground(Color.decode("#ECEBDE"));
        thead.setFont(new Font("Tahome", Font.BOLD, 12));

        JTableHeader thead1 = tblsales.getTableHeader();
        thead1.setForeground(Color.decode("#102C57"));
        thead1.setBackground(Color.decode("#ECEBDE"));
        thead1.setFont(new Font("Tahome", Font.BOLD, 14));

        int stockColumns = tblstock.getColumnModel().getColumnCount();
        int salesColumns = tblsales.getColumnModel().getColumnCount();

        // Dynamically handle column preferences
        for (int i = 0; i < Math.min(stockColumns, salesColumns); i++) {
            TableColumn stockCol = tblstock.getColumnModel().getColumn(i);
            TableColumn salesCol = tblsales.getColumnModel().getColumn(i);
            stockCol.setPreferredWidth(70);
            salesCol.setPreferredWidth(70);
        }
    }


    private void txtcategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcategoryKeyReleased
        
        String category = txtcategory.getText();
        if (txtcategory.getText().length() > 0) {
            try {
                String sql = "SELECT `item_id` as 'Item ID', `item_name` as 'Item Name', `category` as 'Category', `serial_no` as 'Serial No.', `cost_price` as 'Cost Price', `sale_price` as 'Sale Price', `quantity` as 'Quantity', `min_stock` as 'MIN', `max_stock` as 'MAX', `image` as 'Image' FROM `productlist` where category LIKE '%" + category + "%'";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                e.printStackTrace(); // Always print stack trace for debugging
            }
        } else {
            stocklord();
        }
    }//GEN-LAST:event_txtcategoryKeyReleased

    private void btnclearsaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearsaleMouseClicked
        ((JTextField) fdate.getDateEditor().getUiComponent()).setText("");
        ((JTextField) tdate.getDateEditor().getUiComponent()).setText("");

        salelord();
    }//GEN-LAST:event_btnclearsaleMouseClicked

    private void btnclearstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearstockMouseClicked
        txtcategory.setText("");
        stocklord();
    }//GEN-LAST:event_btnclearstockMouseClicked

    private void printstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printstockMouseClicked
        try {
            tblstock.print();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_printstockMouseClicked

    private void printsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printsalesMouseClicked
        try {
            tblsales.print();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_printsalesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclearsale;
    private javax.swing.JButton btnclearstock;
    private javax.swing.JButton btnprocess;
    private com.toedter.calendar.JDateChooser fdate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton printsales;
    private javax.swing.JButton printstock;
    private javax.swing.JTable tblsales;
    private javax.swing.JTable tblstock;
    private com.toedter.calendar.JDateChooser tdate;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalsales;
    private javax.swing.JTextField txtcategory;
    // End of variables declaration//GEN-END:variables
}
